### PR TITLE
Completed TODOs, cleanup

### PR DESCRIPTION
**Pull request by xenago**
- Added the TODO items:
  - logging
  - configurable download path/timezone/delay
  - configurable functionality to skip already-downloaded files (I assume that is what is meant by 'overwrite')
- Added function to download a single video (useful if RipTok is used in a different project as an imported module)
- Reformatted code/cleaned up imports

Feel free to modify as desired!

### CODE REVIEW

**Comment by inobrevi** [comment]
Wow! Very nice! I'm gonna steal some for future projects :D
Merging!

**Comment by inobrevi** [comment]
Wait, I'm new at this. If I close, I can't merge it?
Ok, this works :P

**Comment by xenago** [comment]
Awesome, thanks for the quick response! Please reuse whatever you need and change it how you prefer. I will be sure to send another PR in the future if I make any more improvements.

**Comment by inobrevi** [comment]
2 things I'm thinking about:
- pushing parameters which are now in optional to config file, so you can set them up and forget
- finding a way to download without watermark

I don't know when/if I will have time to get that done, just FYI.

**Pull request merged**
